-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2026-05-26 15:18:07 EEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE stilisti (
    id_stilist NUMBER(2) NOT NULL,
    nume       VARCHAR2(30) NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX stilisti__idx ON
    stilisti (
        id_stilist
    ASC )
        LOGGING;

ALTER TABLE stilisti ADD CONSTRAINT stilisti_pk PRIMARY KEY ( id_stilist );

CREATE TABLE servicii (
    id_serviciu   NUMBER(3) NOT NULL,
    nume          VARCHAR2(30) NOT NULL,
    pret          NUMBER(6, 2) NOT NULL,
    durata_minute NUMBER(3) NOT NULL
)
LOGGING;

ALTER TABLE servicii ADD CONSTRAINT servicii_pret_ck CHECK ( pret >= 0 );

ALTER TABLE servicii ADD CHECK ( durata_minute > 0 );

ALTER TABLE servicii ADD CONSTRAINT servicii_pk PRIMARY KEY ( id_serviciu );

ALTER TABLE servicii ADD CONSTRAINT servicii_nume_un UNIQUE ( nume );

CREATE OR REPLACE FUNCTION func_calc_sfarsit_programare (
    p_id_serviciu    servicii.id_serviciu%TYPE,
    p_ora_programare DATE
) RETURN DATE AS
    v_durata NUMBER;
BEGIN
    SELECT
        durata_minute
    INTO v_durata
    FROM
        servicii
    WHERE
        id_serviciu = p_id_serviciu;

    RETURN p_ora_programare + v_durata / 1440;
EXCEPTION
    WHEN no_data_found THEN
        raise_application_error(-20001, 'Serviciul nu exista');
END;
/

CREATE TABLE programari (
    id_programare      NUMBER(7) NOT NULL,
    id_client          NUMBER(6) NOT NULL,
    id_stilist         NUMBER(2) NOT NULL,
    id_serviciu        NUMBER(3) NOT NULL,
    ora_programare     DATE NOT NULL,
    sfarsit_programare DATE NOT NULL,
    observatii         VARCHAR2(50)
)
LOGGING;

ALTER TABLE programari ADD CONSTRAINT programari_pk PRIMARY KEY ( id_programare );

ALTER TABLE programari ADD CONSTRAINT programari_client_ora__un UNIQUE ( id_client,
                                                                         ora_programare );

ALTER TABLE programari ADD CONSTRAINT programari_stilist_ora__un UNIQUE ( id_stilist,
                                                                          ora_programare );

CREATE OR REPLACE FUNCTION func_stilistul_este_disponibil (
    p_id_stilist    IN stilisti.id_stilist%TYPE,
    p_id_serviciu   IN servicii.id_serviciu%TYPE,
    p_ora_start     IN DATE,
    p_id_programare IN programari.id_programare%TYPE
) RETURN BOOLEAN AS
    v_conflict    NUMBER;
    v_ora_sfarsit DATE;
BEGIN
    v_ora_sfarsit := func_calc_sfarsit_programare(p_id_serviciu, p_ora_start);
    SELECT
        COUNT(*)
    INTO v_conflict
    FROM
        programari
    WHERE
            id_stilist = p_id_stilist
        AND ora_programare < v_ora_sfarsit
        AND sfarsit_programare > p_ora_start
        AND ( p_id_programare IS NULL
              OR id_programare != p_id_programare );

    RETURN v_conflict = 0;
END;
/

CREATE TABLE clienti (
    id_client NUMBER(6) NOT NULL,
    nume      VARCHAR2(30) NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX clienti__idx ON
    clienti (
        id_client
    ASC )
        LOGGING;

ALTER TABLE clienti ADD CONSTRAINT clienti_pk PRIMARY KEY ( id_client );

CREATE TABLE detalii_clienti (
    id_client         NUMBER(6) NOT NULL,
    telefon           VARCHAR2(10) NOT NULL,
    data_inregistrare DATE NOT NULL,
    email             VARCHAR2(30),
    comentarii        VARCHAR2(50)
)
LOGGING;

ALTER TABLE detalii_clienti
    ADD CONSTRAINT clienti_telefon_ck CHECK ( REGEXP_LIKE ( telefon,
                                                            '07[0-9]{8}' ) );

ALTER TABLE detalii_clienti
    ADD CONSTRAINT clienti_email_ck CHECK ( REGEXP_LIKE ( email,
                                                          '[0-9a-z._%-]+@[0-9a-z._%-]+\.[a-z]{2,4}' ) );

CREATE UNIQUE INDEX detalii_clienti__idx ON
    detalii_clienti (
        id_client
    ASC )
        LOGGING;

ALTER TABLE detalii_clienti ADD CONSTRAINT detalii_clienti_pk PRIMARY KEY ( id_client );

ALTER TABLE detalii_clienti ADD CONSTRAINT detalii_clienti_telefon__un UNIQUE ( telefon );

ALTER TABLE detalii_clienti ADD CONSTRAINT detalii_clienti_email__un UNIQUE ( email );

CREATE TABLE detalii_stilisti (
    id_stilist    NUMBER(2) NOT NULL,
    experienta    VARCHAR2(15) NOT NULL,
    data_angajare DATE NOT NULL,
    telefon       VARCHAR2(10) NOT NULL,
    email         VARCHAR2(30) NOT NULL,
    adresa        VARCHAR2(30) NOT NULL
)
LOGGING;

ALTER TABLE detalii_stilisti
    ADD CONSTRAINT detalii_stilisit_experienta_ck
        CHECK ( experienta IN ( 'entry-level', 'mid-level', 'senior-level' ) );

ALTER TABLE detalii_stilisti
    ADD CONSTRAINT setalii_stilisti_telefon_ck CHECK ( REGEXP_LIKE ( telefon,
                                                                     '07[0-9]{8}' ) );

ALTER TABLE detalii_stilisti
    ADD CONSTRAINT detalii_stilisti_email_ck CHECK ( REGEXP_LIKE ( email,
                                                                   '[0-9a-z._%-]+@[0-9a-z._%-]+\.[a-z]{2,4}' ) );

CREATE UNIQUE INDEX detalii_stilisti__idx ON
    detalii_stilisti (
        id_stilist
    ASC )
        LOGGING;

ALTER TABLE detalii_stilisti ADD CONSTRAINT detalii_stilisti_pk PRIMARY KEY ( id_stilist );

ALTER TABLE detalii_stilisti ADD CONSTRAINT detalii_stilisti_telefon_un UNIQUE ( telefon );

ALTER TABLE detalii_stilisti ADD CONSTRAINT detalii_stilisti_email_un UNIQUE ( email );

ALTER TABLE programari
    ADD CONSTRAINT clienti_fk
        FOREIGN KEY ( id_client )
            REFERENCES clienti ( id_client )
            NOT DEFERRABLE;

ALTER TABLE detalii_clienti
    ADD CONSTRAINT detalii_clienti_clienti_fk
        FOREIGN KEY ( id_client )
            REFERENCES clienti ( id_client )
            NOT DEFERRABLE;

ALTER TABLE detalii_stilisti
    ADD CONSTRAINT detalii_stilisti_stilisti_fk
        FOREIGN KEY ( id_stilist )
            REFERENCES stilisti ( id_stilist )
            NOT DEFERRABLE;

ALTER TABLE programari
    ADD CONSTRAINT programari_servicii_fk
        FOREIGN KEY ( id_serviciu )
            REFERENCES servicii ( id_serviciu )
            NOT DEFERRABLE;

ALTER TABLE programari
    ADD CONSTRAINT stilisti_fk
        FOREIGN KEY ( id_stilist )
            REFERENCES stilisti ( id_stilist )
            NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER Trg_Validare_programare 
    BEFORE INSERT OR UPDATE ON Programari 
    FOR EACH ROW 
BEGIN
	IF TO_CHAR(:new.ora_programare, 'DY') IN ('SAT','SUN') THEN
		RAISE_APPLICATION_ERROR(-20001,'Salonul este inchis in weekend');
	END IF;
	
	IF TO_NUMBER(TO_CHAR(:new.ora_programare,'HH24')) <8 OR 
	TO_NUMBER(TO_CHAR(:new.ora_programare, 'HH24')) >= 16 THEN
		RAISE_APPLICATION_ERROR(-20001,'Salonul este deschis intre 8:00 si 16:00');
	END IF;

	IF :new.ora_programare < SYSDATE THEN
		RAISE_APPLICATION_ERROR(-20001,'EROARE: Prog. nu poate fi facuta in trecut');
	END IF;

	IF :new.ora_programare > ADD_MONTHS(SYSDATE,12) THEN
		RAISE_APPLICATION_ERROR(-20001,'EROARE: Prog. nu poate fi facuta cu mai mult de 1 an inainte');
	END IF;
	

	:new.sfarsit_programare := Func_calc_sfarsit_programare(:new.id_serviciu,:new.ora_programare);
	
END; 
/

CREATE OR REPLACE PACKAGE Package_programari AS 
  FUNCTION calc_pret_client(
  p_id_client IN Programari.id_client%TYPE,
  p_zi IN DATE) RETURN NUMBER;
  
  FUNCTION Func_cauta_stilist_liber (
    p_id_serviciu IN Servicii.id_serviciu%type,
    p_ora_start IN DATE,
    p_id_stilist IN Stilisti.id_stilist%TYPE
    ) RETURN Stilisti.id_stilist%type; 
    
  PROCEDURE Proc_adauga_programare(
        p_id_client IN Programari.id_client%TYPE,
        p_id_serviciu IN Programari.id_serviciu%TYPE,
        p_ora_start IN DATE);
        
  PROCEDURE Proc_modifica_programare(
    p_id_programare IN Programari.id_programare%TYPE,
    p_ora_noua IN DATE);
    
  PROCEDURE Proc_sterge_prog_stilist(
    p_id_stilist IN Stilisti.id_stilist%TYPE,
    p_zi IN  DATE);
    
END Package_programari;
/

CREATE OR REPLACE PACKAGE BODY package_programari AS 

  ---------------------------------------------------
  -- Afiseaza pret client pentru o zi
  ---------------------------------------------------
    FUNCTION calc_pret_client (
        p_id_client IN programari.id_client%TYPE,
        p_zi        IN DATE
    ) RETURN NUMBER AS
        v_pret NUMBER := 0;
    BEGIN
        SELECT
            nvl(
                sum(s.pret),
                0
            )
        INTO v_pret
        FROM
            servicii   s,
            programari p
        WHERE
                s.id_serviciu = p.id_serviciu
            AND p.id_client = p_id_client
            AND trunc(p.ora_programare) = trunc(p_zi);

        RETURN v_pret;
    END;
  
  ---------------------------------------------------
  -- Cauta stilist liber pentru o programare
  ---------------------------------------------------
    FUNCTION func_cauta_stilist_liber (
        p_id_serviciu IN servicii.id_serviciu%TYPE,
        p_ora_start   IN DATE,
        p_id_stilist  IN stilisti.id_stilist%TYPE
    ) RETURN stilisti.id_stilist%TYPE AS

        v_id_returnat stilisti.id_stilist%TYPE;
        v_ora_sfarsit DATE;
        e_niciun_stilist EXCEPTION;
        CURSOR c_stilisti IS
        SELECT
            s.id_stilist,
            nvl(
                sum((p.sfarsit_programare - p.ora_programare) * 1440),
                0
            ) AS minute_lucrate
        FROM
            stilisti   s
            LEFT JOIN programari p ON s.id_stilist = p.id_stilist
                                      AND trunc(p.ora_programare) = trunc(p_ora_start)
        WHERE
            p_id_stilist IS NULL
            OR p_id_stilist != s.id_stilist
        GROUP BY
            s.id_stilist
        ORDER BY
            minute_lucrate ASC;

        v_rec         c_stilisti%rowtype;
    BEGIN
        v_ora_sfarsit := func_calc_sfarsit_programare(p_id_serviciu, p_ora_start);
        OPEN c_stilisti;
        LOOP
            FETCH c_stilisti INTO v_rec;
            EXIT WHEN c_stilisti%notfound;
            IF func_stilistul_este_disponibil(v_rec.id_stilist, p_id_serviciu, p_ora_start, NULL) THEN
                v_id_returnat := v_rec.id_stilist;
                EXIT;
            END IF;

        END LOOP;

        CLOSE c_stilisti;
        IF v_id_returnat IS NULL THEN
            RAISE e_niciun_stilist;
        END IF;
        RETURN v_id_returnat;
    EXCEPTION
        WHEN e_niciun_stilist THEN
            raise_application_error(-20001, 'Nu exista niciun stilist disponibil in acest interval');
    END;

  ---------------------------------------------------
  -- Adauga o programare
  ---------------------------------------------------
    PROCEDURE proc_adauga_programare (
        p_id_client   IN programari.id_client%TYPE,
        p_id_serviciu IN programari.id_serviciu%TYPE,
        p_ora_start   IN DATE
    ) AS
        v_id_stilist stilisti.id_stilist%TYPE;
        e_insert_esuat EXCEPTION;
    BEGIN
        v_id_stilist := func_cauta_stilist_liber(p_id_serviciu, p_ora_start, NULL);
        INSERT INTO programari (
            id_client,
            id_serviciu,
            id_stilist,
            ora_programare
        ) VALUES ( p_id_client,
                   p_id_serviciu,
                   v_id_stilist,
                   p_ora_start );

        COMMIT;
        dbms_output.put_line('Programare adaugata cu succes');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            raise_application_error(-20001, sqlerrm);
    END proc_adauga_programare;
    
  ---------------------------------------------------
  -- Modifica ora unei programari
  ---------------------------------------------------
    PROCEDURE proc_modifica_programare (
        p_id_programare IN programari.id_programare%TYPE,
        p_ora_noua      IN DATE
    ) AS

        v_id_serviciu    programari.id_serviciu%TYPE;
        v_id_stilist     programari.id_stilist%TYPE;
        v_id_stilist_nou programari.id_stilist%TYPE;
    BEGIN
        SELECT
            id_serviciu,
            id_stilist
        INTO
            v_id_serviciu,
            v_id_stilist
        FROM
            programari
        WHERE
            id_programare = p_id_programare;

        IF func_stilistul_este_disponibil(v_id_stilist, v_id_serviciu, p_ora_noua, p_id_programare) THEN
            v_id_stilist_nou := v_id_stilist;
        ELSE
            v_id_stilist_nou := func_cauta_stilist_liber(v_id_serviciu, p_ora_noua, NULL);
            dbms_output.put_line('Stilistul s-a schimbat');
        END IF;

        UPDATE programari
        SET
            ora_programare = p_ora_noua,
            id_stilist = v_id_stilist_nou
        WHERE
            id_programare = p_id_programare;

        COMMIT;
        dbms_output.put_line('Programare modificata cu succes');
    EXCEPTION
        WHEN no_data_found THEN
            ROLLBACK;
            raise_application_error(-20001, 'Id programare invalid');
        WHEN OTHERS THEN
            ROLLBACK;
            raise_application_error(-20001, 'Eroare la modificare: ' || sqlerrm);
    END proc_modifica_programare; 
  
  ---------------------------------------------------
  -- Elimina programarile unui stilist intr-o zi
  ---------------------------------------------------
    PROCEDURE proc_sterge_prog_stilist (
        p_id_stilist IN stilisti.id_stilist%TYPE,
        p_zi         IN DATE
    ) AS

        v_stilist_nou stilisti.id_stilist%TYPE;
        CURSOR c_programari IS
        SELECT
            id_programare,
            id_serviciu,
            ora_programare
        FROM
            programari
        WHERE
                id_stilist = p_id_stilist
            AND trunc(ora_programare) = trunc(p_zi)
        FOR UPDATE;

    BEGIN
        FOR v_rec IN c_programari LOOP
            BEGIN
                v_stilist_nou := func_cauta_stilist_liber(v_rec.id_serviciu, v_rec.ora_programare, p_id_stilist);
                UPDATE programari
                SET
                    id_stilist = v_stilist_nou
                WHERE
                    id_programare = v_rec.id_programare;

                dbms_output.put_line('Programarea '
                                     || v_rec.id_programare
                                     || ' reasignata stilistului '
                                     || v_stilist_nou);
            EXCEPTION
                WHEN OTHERS THEN
                    DELETE FROM programari
                    WHERE
                        id_programare = v_rec.id_programare;

                    dbms_output.put_line('Programarea '
                                         || v_rec.id_programare
                                         || ' stearsa — niciun stilist disponibil');
            END;
        END LOOP;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            raise_application_error(-20001, 'Eroare la modificare programari: ' || sqlerrm);
    END;

END package_programari;
/

CREATE SEQUENCE clienti_id_client_seq START WITH 100000 MINVALUE 100000 MAXVALUE 999999 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER clienti_id_client_trg BEFORE
    INSERT ON clienti
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := clienti_id_client_seq.nextval;
END;
/

CREATE SEQUENCE programari_id_programare_seq START WITH 1000000 MINVALUE 1000000 MAXVALUE 9999999 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER programari_id_programare_trg BEFORE
    INSERT ON programari
    FOR EACH ROW
    WHEN ( new.id_programare IS NULL )
BEGIN
    :new.id_programare := programari_id_programare_seq.nextval;
END;
/

CREATE SEQUENCE servicii_id_serviciu_seq START WITH 100 MINVALUE 100 MAXVALUE 999 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER servicii_id_serviciu_trg BEFORE
    INSERT ON servicii
    FOR EACH ROW
    WHEN ( new.id_serviciu IS NULL )
BEGIN
    :new.id_serviciu := servicii_id_serviciu_seq.nextval;
END;
/

CREATE SEQUENCE stilisti_id_stilist_seq START WITH 10 MINVALUE 10 MAXVALUE 99 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER stilisti_id_stilist_trg BEFORE
    INSERT ON stilisti
    FOR EACH ROW
    WHEN ( new.id_stilist IS NULL )
BEGIN
    :new.id_stilist := stilisti_id_stilist_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             4
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           1
-- CREATE PACKAGE BODY                      1
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          2
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
